version: '3.2'

services:
   mysql:
      image: mysql
      container_name: my-mysql
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: password
      volumes:
        - mysql-data:/var/lib/mysql

#  phpmyadmin:
#     depends_on:
#      - mysql
#     image: phpmyadmin/phpmyadmin
#     container_name: my-phpmyadmin
#     restart: always
#     ports:
#      - '8081:80'
#     environment:
#       PMA_HOST: mysql

volumes:
    mysql-data:
